name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install pnpm CLI
        run: npm install -g pnpm
      - name: Install pnpm dependencies
        run: pnpm install --frozen-lockfile
      - name: Build React vite app
        run: pnpm build
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_REM_WASTE_SKIP_SIZE }}
          channelId: live
          projectId: rem-waste-skip-size